[colors.bright]
black = "0x585858"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xf8f8f8"
yellow = "0xf7ca88"

[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"
